# @package _global_


model:
  name: birnni
  hparams:
    hidden_size: 64
    cell: 'gru'
    concat_mask: True
    detach_input: False
    fully_connected: False
    n_layers: 1
    cat_states_layers: False

dataset:
  connectivity:
    layout: csr

mask_as_exog: True