# @package _global_

#### Configuration for Dataset and Model Parameters ############################

dataset:
  params:
    val_len: 0.1
    window: 24  
    stride: 1

training:
  hparams:
    whiten_prob: [0.2, 0.5, 0.8]
    scale_target: True
    epochs: 300
    loss_fn: l1_loss
    lr_scheduler: magic
    lr: 0.0008
    patience: 40
    precision: 16
    batch_size: 8
    batch_inference: 20
    batches_epoch: 300

model:
  name: spin-h
  hparams:
    h_size: 32
    z_size: 128
    z_heads: 4
    eta: 3
    n_layers: 5
    message_layers: 1
    update_z_cross: False
    norm: True
    spatial_aggr: 'softmax'
  
mask_as_exog: False