# @package _global_

#### Model params #############################################################
model:
  name: stcn
  hparams:
    hidden_size: 32
    ff_size: 256
    n_layers: 4
    dropout: 0.1
    temporal_kernel_size: 2
    spatial_kernel_size: 2
    dilation: 2
    norm: batch

#### Config overrides #########################################################
dataset:
  connectivity:
    layout: csr  


mask_as_exog: False