# @package _global_

#### Model params #############################################################
model:
  name: tts_amp
  hparams:           
    hidden_size: 32
    emb_size: 10           
    add_embedding_before: 'encoding'
    use_local_weights: null 
    time_layers: 1
    graph_layers: 1
    activation: 'elu'

#### Config overrides #########################################################
dataset:
  connectivity:
    layout: csr  # set this to use efficient message-passing implementation
                
