# @package _global_

#### Model params #############################################################
model:
  name: tts_imp
  hparams:
    hidden_size: 64  # 64, 32
    emb_size: 32  # 32, 16
    add_embedding_before: ['encoding', 'decoding']
    use_local_weights: null # ['encoder', 'decoder']
    root_weight: True
    time_layers: 1
    graph_layers: 2  # 2, 4
    add_backward: True  # True if adj is asymmetric
    norm: 'asym'
    cached: True
    activation: 'elu'

#### Config overrides #########################################################
dataset:
  connectivity:
    layout: csr  # set this to use efficient message-passing implementation

