defaults:
  - _self_
  - logger: null
  - optimizer: adam
  - lr_scheduler: multistep
  - dataset: la
  - model: rnn
  - imputation_model: none
   

#### Experiment params ########################################################
hydra:
  run:
    dir: logs/${model.name}/${dataset.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: logs/${now:%Y-%m-%d-%H-%M-%S}
    subdir: ${model.name}/${dataset.name}/${hydra.job.num}

tags: ${cat:${default_tags},${run_tags}}

###### Load imputation from #######################


dir_imputation: "imputed_val/${imputation_model.name}/${dataset.name}"


default_tags:
  - ${model.name}
  - ${dataset.name}
  - ${imputation_model.name}

run_tags: []

workers: 0
num_threads: 1

mask_as_exog: True

#### Windowing params #########################################################
window: 12
horizon: 12
stride: 1


#### Training params ##########################################################
epochs: 200
patience: 30
batch_size: 32
train_batches: 300  # 1.0
grad_clip_val: 5
scaler:
  method: Standard
  axis: graph
  scale_target: False



