# @package _global_
defaults:
  - _self_
  - missing@dataset.missing: normal  # normal, point

#### Dataset params ###########################################################
dataset:
  name: air_${dataset.missing.name}
  missing:
    seed: 437   # also number of nodes
    min_seq: 4  # 4 hours
    max_seq: 12 # 12 hours
  splitting:
    method: air_quality
    val_len: 0.1
  connectivity:
    method: distance
    threshold: 0.1
    include_self: False
    layout: csr
  covariates:
    year: True
    day: True
    weekday: True
    mask: True
    std: True
    mean: True 

#### Windowing params #########################################################
window: 12
horizon: 12
stride: 1

scaler:
  method: Standard
  axis: graph
  scale_target: False
